name: update_crashes

on:
  schedule:
    - cron: '0 10 12 * *'
  workflow_dispatch:


jobs:
  update_crashes:
    runs-on: macOS-latest
    env:
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install required packages
        run: Rscript -e 'install.packages(c("pins", "sf"), type = "mac.binary", dependencies = TRUE)'
      - name: Run R script to update crashes
        run: Rscript update_crash_data.R