name: update_crashes

on:
  schedule:
    - cron: '7 0 * * 0' #run on Sundays at 00:07
  workflow_dispatch:


jobs:
  update_crashes:
    runs-on: macOS-latest
    env:
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install required packages
        run: Rscript -e 'install.packages(c("pins", "sf", "lubridate", "purrr"), type = "mac.binary", dependencies = TRUE)'
      - name: Run R script to update crashes
        run: Rscript update_crash_data.R